version: '3.6'
services:
  redis:
    image: "redis:6.2.6-alpine"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
